apiVersion: v1
kind: Pod
metadata: 
  name: mypod
spec:
  initContainers:
  - name: c01
    image: httpd
    command: ["/bin/bash", "-c", "echo hai loki> /tmp/data/testfile; sleep 10"]
    volumeMounts:
    - name: myvol
      mountPath: /tmp/data
  containers:
  - name: c02
    image: tomcat
    command: ["/bin/bash", "-c", "while true; do cat /tmp/data/testfile; sleep 10; done"]
    volumeMounts:
    - name: myvol
      mountPath: /tmp/data
  volumes:
  - name: myvol