apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: c01
    image: httpd
    ports:
    - containerPort: 80
    volumeMounts:
    - name: v1
      mountPath: /tmp/c01
  - name: c02
    image: tomcat
    ports:
    - containerPort: 80
    volumeMounts:
    - name: v1
      mountPath: /tmp/c02
  volumes:
  - name: v1