apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep
spec:
  replicas: 2
  selector:
    matchLabels:
      name: dep
  template:
    metadata:
      name: mytestpod
      labels: 
        name: dep
    spec:
      containers:
      - name: c01
        image: httpd
        ports:
        - containerPort: 80
        volumeMounts:
        - name: myvol
          mountPath: /tmp/loki
      volumes: 
      - name: myvol
        persistentVolumeClaim:
          claimName: mypvclaim
    