apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dep
  template:
    metadata:
      name: mydeploypod
      labels:
        name: dep
    spec: 
      containers:
      - name: c01
        image: httpd
        resources:
          limits:
            cpu: "500m"
          requests:
            cpu: "200m"