apiVersion: v1
kind: Pod
metadata:
  name: mypod-mc
  annotations:
    description: this is multicontainer pod
spec:
  containers:
  - name: c01
    image: httpd
    command: ["/bin/bash", "-c", "while true; do echo lokesh you are in container 1; sleep 5; done"]
  - name: c02
    image: tomcat
    command: ["/bin/bash", "-c", "while true; do echo lokesh you are in container 2; sleep 5; done"]