apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: c01
    image: httpd
    volumeMounts:
    - name: myvol1
      mountPath: /tmp/secrets
  volumes:
  - name: myvol1
    secret:
      secretName: mysecret