apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: c01
    image: httpd
    ports:
    - containerPort: 80
  - name: c02
    image: tomcat
    ports:
    - containerPort: 8080