apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc
spec:
  replicas: 2
  selector: 
    name: rc
  template:
    metadata:
      name: testpod
      labels:
        name: rc
    spec:
      containers:
      - name: testpod
        image: httpd
        ports:
        - containerPort: 80